/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.inf.languages.turtles.ide


/**
 * Use this class to register ide components.
 */
class TurtlesLanguageIdeModule extends AbstractTurtlesLanguageIdeModule {
}
