/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.inf.languages.turtles.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class TurtlesLanguageProposalProvider extends AbstractTurtlesLanguageProposalProvider {
}
