/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.inf.languages.turtles


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TurtlesLanguageStandaloneSetup extends TurtlesLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new TurtlesLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
